### PR TITLE
Add actions for buttons and knob button

### PR DESCRIPTION
**Pull request by zingo**
Signed-off-by: Zingo Andersen <zingo.andersen@arm.com>

### CODE REVIEW

**Comment by zingo** [comment]
I had a boring meeting at work so I added so you can mute/unmute the mic (and in zoom at the same time) and fixed so you can add actions to the buttons also.

**Comment by zingo** [comment]
Aslo I used xdotool in my example, but it only work in x11, so this might need to be reworked or maybe just mentioned in the README.md as example setup.

The nice thing when using
xdotool key XF86AudioLowerVolume
is at least in my system (Ubuntu 20.04) that I get the nice GUI popups from the system showing the change.

**Comment by instance-id** [comment]
I am not sure I want to merge in a change to the config commands just yet (ex. the volume command change), as then it would conflict with what I am actually using. I would have just committed a blank config, but the way it has to be used for commands to function how I wanted makes it overall a bit more complex than most configs would be, so including my actual config was kind if necessary. I used the commands I did because I use Wayland and have a Pipewire setup that for my monitor speakers and an output to a stereo, and doing it that way allowed me to control both. For whatever reason using XF86Audio only controlled one active output.

Though, I am good with the button changes, I think I might have missed them when doing a rename/refactor, and was not actively using them, so I don't remember if they were working or not when I uploaded this.

That said, I recently became a fan of using a '[justfile](https://github.com/instance-id/lapce-powershell-plugin/blob/master/justfile)' (basically a more versatile build/make file that can be used for more general and 'whatever you want' actions). I am thinking that I could either make a commit/pull 'just' setup on my end, in which when committing, it turns my config into something like example.config, and replaces the current config with an empty one, then another for if I pull, it then replaces the blank one with my actual. I also am thinking that taking all of my individual commands and putting them into an "example commands' section in the read me, or a wiki page, then there could be mine, as well as yours, and then there could be multiple examples of how to go about using the knobs/buttons, etc and someone could just copy in the one that works best for them into their config.

**Comment by zingo** [comment]
> I am not sure I want to merge in a change to the config commands 

No problem, I kind of wondered about that, Ill create an update patch that clean it out and just adds the buttons, and maybe put the examples in the readme we will see :) . That should be good enough if anyone else finds and use this :)

Thanks for starting this, now I finally have very nice buttons for my work.
Some initial testing it seams very stable to connect&disconnect the device, this will be great as I can connecting it to my monitor USB hub and it will auto-switch the buttons the the home/work setup depending in my "kvm" switch together with monitor,mouse,keyboard :)

**Pull request merged**
